name: Build and Release .NET App

on:
  push:
    tags:
      - 'v*' # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish as single file
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish

    - name: Rename output executable
      run: mv ./publish/*.exe ./publish/myapp.exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/myapp.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
